version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravelapp
        container_name: laravelapp
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: laravelapp
            SERVICE_TAGS: dev
        working_dir: /app

        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - laravel

volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
